In [61]:
# Import Libraries to read and plot datasets
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

In [62]:
#Read csv file
crash_data = pd.read_csv("hq1d-p-app52dopendataexport2025crashes.csv")

C:\Users\Evan\AppData\Local\Temp\ipykernel_36116\3571351588.py:2: DtypeWarning: Columns (4,12,13,23,24,34,43,53,60,64,65,67,68,69,70,71,72,73) have mixed types. Specify dtype option on import or set low_memory=False.
  crash_data = pd.read_csv("hq1d-p-app52dopendataexport2025crashes.csv")

In [63]:
crash_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 393510 entries, 0 to 393509
Data columns (total 74 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Collision Id                        393510 non-null  int64
 1   Report Number                       393439 non-null  object
 2   Report Version                      393510 non-null  int64
 3   Is Preliminary                      393510 non-null  bool
 4   NCIC Code                           393510 non-null  object
 5   Crash Date Time                     393510 non-null  object
 6   Crash Time Description              393510 non-null  int64
 7   Beat                                373664 non-null  object
 8   City Id                             393471 non-null  float64
 9   City Code                           393471 non-null  float64
 10  City Name                           393471 non-null  object
 11  County Code                         393471 non-null  float64
 12  City Is Active                      393471 non-null  object
 13  City Is Incorporated                393471 non-null  object
 14  Collision Type Code                 392585 non-null  object
 15  Collision Type Description          392585 non-null  object
 16  Collision Type Other Desc           7120 non-null    object
 17  Day Of Week                         393510 non-null  object
 18  DispatchNotified                    297092 non-null  object
 19  HasPhotographs                      202334 non-null  object
 20  HitRun                              94142 non-null   object
 21  IsAttachmentsMailed                 0 non-null       float64
 22  IsDeleted                           393510 non-null  bool
 23  IsHighwayRelated                    393509 non-null  object
 24  IsTowAway                           393411 non-null  object
 25  JudicialDistrict                    293857 non-null  object
 26  MotorVehicleInvolvedWithCode        392430 non-null  object
 27  MotorVehicleInvolvedWithDesc        392430 non-null  object
 28  MotorVehicleInvolvedWithOtherDesc   66810 non-null   object
 29  NumberInjured                       374620 non-null  float64
 30  NumberKilled                        373957 non-null  float64
 31  Weather 1                           392054 non-null  object
 32  Weather 2                           9752 non-null    object
 33  Road Condition 1                    392248 non-null  object
 34  Road Condition 2                    954 non-null     object
 35  Special Condition                   25286 non-null   object
 36  LightingCode                        392712 non-null  object
 37  LightingDescription                 392712 non-null  object
 38  Latitude                            307411 non-null  float64
 39  Longitude                           307428 non-null  float64
 40  MilepostDirection                   921 non-null     object
 41  MilepostDistance                    1002 non-null    float64
 42  MilepostMarker                      1002 non-null    object
 43  MilepostUnitOfMeasure               703 non-null     object
 44  PedestrianActionCode                391099 non-null  object
 45  PedestrianActionDesc                391099 non-null  object
 46  PreparedDate                        223774 non-null  object
 47  Primary Collision Factor Code       393246 non-null  object
 48  Primary Collision Factor Violation  371948 non-null  object
 49  PrimaryCollisionFactorIsCited       292912 non-null  object
 50  PrimaryCollisionPartyNumber         363355 non-null  float64
 51  PrimaryRoad                         393510 non-null  object
 52  ReportingDistrict                   126416 non-null  object
 53  ReportingDistrictCode               124 non-null     object
 54  ReviewedDate                        312072 non-null  object
 55  RoadwaySurfaceCode                  392533 non-null  object
 56  SecondaryDirection                  298292 non-null  object
 57  SecondaryDistance                   301116 non-null  float64
 58  SecondaryRoad                       393266 non-null  object
 59  SecondaryUnitOfMeasure              301116 non-null  object
 60  SketchDesc                          741 non-null     object
 61  TrafficControlDeviceCode            392609 non-null  object
 62  CreatedDate                         393510 non-null  object
 63  ModifiedDate                        393510 non-null  object
 64  IsCountyRoad                        213905 non-null  object
 65  IsFreeway                           213905 non-null  object
 66  CHP555Version                       393510 non-null  int64
 67  IsAdditonalObjectStruck             23003 non-null   object
 68  NotificationDate                    214360 non-null  object
 69  NotificationTimeDescription         214353 non-null  object
 70  HasDigitalMediaFiles                179067 non-null  object
 71  EvidenceNumber                      47613 non-null   object
 72  IsLocationReferToNarrative          11266 non-null   object
 73  IsAOIOneSameAsLocation              198360 non-null  object
dtypes: bool(2), float64(11), int64(4), object(57)
memory usage: 216.9+ MB

In [64]:
parties_data = pd.read_csv("a2676918-a825-4b77-8e5c-6eadb38d6b1a.csv")

In [65]:
parties_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767052 entries, 0 to 767051
Data columns (total 49 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   _id                               767052 non-null  int64
 1   PartyId                           767052 non-null  int64
 2   CollisionId                       767052 non-null  int64
 3   PartyNumber                       767052 non-null  int64
 4   PartyType                         767052 non-null  object
 5   IsAtFault                         363375 non-null  object
 6   IsOnDutyEmergencyVehicle          738202 non-null  object
 7   IsHitAndRun                       416673 non-null  object
 8   AirbagCode                        659124 non-null  object
 9   AirbagDescription                 659124 non-null  object
 10  SafetyEquipmentCode               651212 non-null  object
 11  SafetyEquipmentDescription        651212 non-null  object
 12  Special Information               704157 non-null  object
 13  Other Associate Factor            746281 non-null  object
 14  Inattention                       9572 non-null    object
 15  DirectionOfTravel                 748054 non-null  object
 16  StreetOrHighwayName               603063 non-null  object
 17  SpeedLimit                        574597 non-null  float64
 18  MovementPrecCollCode              754487 non-null  object
 19  MovementPrecCollDescription       754487 non-null  object
 20  SobrietyDrugPhysicalCode1         753675 non-null  object
 21  SobrietyDrugPhysicalDescription1  753675 non-null  object
 22  SobrietyDrugPhysicalCode2         6022 non-null    object
 23  SobrietyDrugPhysicalDescription2  6022 non-null    object
 24  GenderCode                        653082 non-null  object
 25  GenderDescription                 653082 non-null  object
 26  StatedAge                         505407 non-null  float64
 27  DriverLicenseClass                599412 non-null  object
 28  DriverLicenseStateCode            600296 non-null  object
 29  RaceCode                          624068 non-null  object
 30  RaceDesc                          624068 non-null  object
 31  Vehicle1TypeId                    759025 non-null  float64
 32  Vehicle1TypeDesc                  759025 non-null  object
 33  Vehicle1Year                      687307 non-null  float64
 34  Vehicle1Make                      704036 non-null  object
 35  Vehicle1Model                     556040 non-null  object
 36  Vehicle1Color                     562287 non-null  object
 37  V1IsVehicleTowed                  409743 non-null  object
 38  Vehicle2TypeId                    19805 non-null   float64
 39  Vehicle2TypeDesc                  19805 non-null   object
 40  Vehicle2Year                      18125 non-null   float64
 41  Vehicle2Make                      19225 non-null   object
 42  Vehicle2Model                     18183 non-null   object
 43  Vehicle2Color                     18940 non-null   object
 44  V2IsVehicleTowed                  0 non-null       float64
 45  Lane                              494219 non-null  object
 46  ThruLanes                         492493 non-null  float64
 47  TotalLanes                        494294 non-null  float64
 48  IsDREConducted                    416565 non-null  object
dtypes: float64(9), int64(4), object(36)
memory usage: 286.8+ MB

In [66]:
parties_data.head(1)

,_id,PartyId,CollisionId,PartyNumber,PartyType,IsAtFault,IsOnDutyEmergencyVehicle,IsHitAndRun,AirbagCode,AirbagDescription,...,Vehicle2TypeDesc,Vehicle2Year,Vehicle2Make,Vehicle2Model,Vehicle2Color,V2IsVehicleTowed,Lane,ThruLanes,TotalLanes,IsDREConducted
0,1,13900346,4541902,1,Driver,True,False,True,B,UNKNOWN,...,NaN,NaN,NaN,NaN,NaN,NaN,N/B,1.0,1.0,False

In [67]:
crash_data.head(1)

,Collision Id,Report Number,Report Version,Is Preliminary,NCIC Code,Crash Date Time,Crash Time Description,Beat,City Id,City Code,...,IsCountyRoad,IsFreeway,CHP555Version,IsAdditonalObjectStruck,NotificationDate,NotificationTimeDescription,HasDigitalMediaFiles,EvidenceNumber,IsLocationReferToNarrative,IsAOIOneSameAsLocation
0,4550265,9685-2025-00096,1,False,9685,1/18/2025 3:20:00 PM,1520,039,994.0,3300.0,...,False,False,4,NaN,1/18/2025 3:25:00 PM,1525,False,NaN,NaN,True

Remove Columns that would not be helpful in the overall analysis since it would not provide any meaningful information or lack of background knowledge would provide any benefit

In [83]:
crash_reduced_info = crash_data.drop(['Report Number','Report Version','Is Preliminary','NCIC Code','Beat','City Id','City Code','County Code','City Is Active','City Is Incorporated','Collision Type Code', \
                                    'Collision Type Other Desc', 'DispatchNotified','HasPhotographs','HitRun','IsDeleted','JudicialDistrict','MotorVehicleInvolvedWithOtherDesc','Weather 2','Road Condition 2','LightingCode','MilepostDirection','MilepostDistance','MilepostMarker','MilepostUnitOfMeasure',\
                                    'PreparedDate','Primary Collision Factor Code', 'PrimaryCollisionPartyNumber','ReportingDistrict','ReportingDistrictCode','ReviewedDate','RoadwaySurfaceCode','SecondaryDirection','SecondaryRoad',\
                                      'SecondaryUnitOfMeasure','SketchDesc', 'CreatedDate','ModifiedDate','CHP555Version','IsAdditonalObjectStruck','NotificationDate','NotificationTimeDescription','HasDigitalMediaFiles','EvidenceNumber',\
                                    'IsLocationReferToNarrative','IsAOIOneSameAsLocation','IsAttachmentsMailed'],axis = 1)

In [84]:
crash_reduced_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 393510 entries, 0 to 393509
Data columns (total 27 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Collision Id                        393510 non-null  int64
 1   Crash Date Time                     393510 non-null  object
 2   Crash Time Description              393510 non-null  int64
 3   City Name                           393471 non-null  object
 4   Collision Type Description          392585 non-null  object
 5   Day Of Week                         393510 non-null  object
 6   IsHighwayRelated                    393509 non-null  object
 7   IsTowAway                           393411 non-null  object
 8   MotorVehicleInvolvedWithCode        392430 non-null  object
 9   MotorVehicleInvolvedWithDesc        392430 non-null  object
 10  NumberInjured                       374620 non-null  float64
 11  NumberKilled                        373957 non-null  float64
 12  Weather 1                           392054 non-null  object
 13  Road Condition 1                    392248 non-null  object
 14  Special Condition                   25286 non-null   object
 15  LightingDescription                 392712 non-null  object
 16  Latitude                            307411 non-null  float64
 17  Longitude                           307428 non-null  float64
 18  PedestrianActionCode                391099 non-null  object
 19  PedestrianActionDesc                391099 non-null  object
 20  Primary Collision Factor Violation  371948 non-null  object
 21  PrimaryCollisionFactorIsCited       292912 non-null  object
 22  PrimaryRoad                         393510 non-null  object
 23  SecondaryDistance                   301116 non-null  float64
 24  TrafficControlDeviceCode            392609 non-null  object
 25  IsCountyRoad                        213905 non-null  object
 26  IsFreeway                           213905 non-null  object
dtypes: float64(5), int64(2), object(20)
memory usage: 81.1+ MB